### ISSUE TITLE
Show bills in qb-phone

### ISSUE THREAD

**Issue by tafabdel** [Giana/g-billing#7]
hello i need to know if they are a way to show bills in the qb-phone bills application ? sorry for my english its not my language

**Comment by Giana** [comment]
@tafabdel That is not possible with this code currently. I chose to keep this billing system as a separate system from the qb-phone billing system because there are many issues that can arise from combining this with qb-phone and it would make this script more difficult to maintain.

If you want to disable the /bill command from qb-phone to use g-billing alone in your server, you can reference this issue: https://github.com/Giana/g-billing/issues/3

**Comment by tafabdel** [comment]
ok thank you i try this
